
name: JSON Validation

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Validate JSONs
      run: |
        json_files=$(find . -name "*.json")

        # Validate JSON files
        for file in $json_files
        do
            echo "Validating $file"
            result=$(python -m json.tool "$file")
            if [ $? -ne 0 ]; then
                echo "Invalid JSON file: $file"
                exit 1
            fi
        done
